/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Random;
import static javaapplication1.Playervspc.hasar2;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author bayram
 */
public class bilgisayarvsbilgisayar extends javax.swing.JFrame {

   int pc2atılankart,pc1atılankart;
    int ortadakibuton;
    int hasarpuani;
    int pc1kartsayisi=0,pc2kartsayisi,kartsec=0,pckart=0;
    int x,y,son=0;
    int bilg1skor=0,bilg2skor=0;
    ArrayList<Integer> yerdekipokemonlar=new ArrayList<>();
    ArrayList<Integer> pcpokemonlar2=new ArrayList<>();
    ArrayList<Integer> pcpokemonlar1=new ArrayList<>();
    static int hasar1,hasar2;
     charmander charmander=new charmander();
    Pokemon pokemon1=charmander;
    butterfree butterfree=new butterfree();
    Pokemon pokemon2=butterfree;
    jigglypuff jigglypuff=new jigglypuff();
    Pokemon pokemon3=jigglypuff;
    bulbasaur bulbasaur=new bulbasaur();
    Pokemon pokemon4=bulbasaur;
    meowth meowth=new meowth();
    Pokemon pokemon5=meowth;
    pikachu pikachu=new pikachu();
    Pokemon pokemon6=pikachu;
    psyduck psyduck=new psyduck();
    Pokemon pokemon7=psyduck;
    squirtle squirtle=new squirtle();
    Pokemon pokemon8=squirtle;
    zubat zubat=new zubat();
    Pokemon pokemon9=zubat;
    snorlax snorlax=new snorlax();
    Pokemon pokemon10=snorlax;
    Random rand = new Random();
    public bilgisayarvsbilgisayar() {
        initComponents();
        jButton16.setVisible(false);
        jButton15.setVisible(false);
        jButton14.setVisible(false);
        jButton13.setVisible(false);
        jButton12.setVisible(false);
        jButton11.setVisible(false);
        jButton21.setVisible(false);
        jButton20.setVisible(false);
        for (int i = 0; i <10; i++) {
           yerdekipokemonlar.add(i);           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/charmander.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 320, 200, 280);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/butterfree.png"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 320, 200, 280);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bulbasaur.png"))); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 320, 200, 280);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jigglypuff.png"))); // NOI18N
        getContentPane().add(jButton4);
        jButton4.setBounds(640, 320, 200, 280);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/meowth.png"))); // NOI18N
        getContentPane().add(jButton5);
        jButton5.setBounds(840, 320, 200, 280);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pikachu.png"))); // NOI18N
        getContentPane().add(jButton6);
        jButton6.setBounds(40, 600, 200, 280);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/psyduck.png"))); // NOI18N
        getContentPane().add(jButton7);
        jButton7.setBounds(240, 600, 200, 280);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/squirtle.png"))); // NOI18N
        getContentPane().add(jButton8);
        jButton8.setBounds(440, 600, 200, 280);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/zubat.png"))); // NOI18N
        getContentPane().add(jButton9);
        jButton9.setBounds(640, 600, 200, 280);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/snorlax.png"))); // NOI18N
        getContentPane().add(jButton10);
        jButton10.setBounds(840, 600, 200, 280);
        getContentPane().add(jButton11);
        jButton11.setBounds(1220, 790, 200, 280);
        getContentPane().add(jButton12);
        jButton12.setBounds(1460, 790, 200, 280);
        getContentPane().add(jButton13);
        jButton13.setBounds(1700, 790, 200, 280);
        getContentPane().add(jButton14);
        jButton14.setBounds(1220, 10, 200, 280);
        getContentPane().add(jButton15);
        jButton15.setBounds(1460, 10, 200, 280);
        getContentPane().add(jButton16);
        jButton16.setBounds(1700, 10, 200, 280);
        getContentPane().add(jButton17);
        jButton17.setBounds(1270, 420, 200, 280);
        getContentPane().add(jButton18);
        jButton18.setBounds(1540, 420, 200, 280);

        jButton19.setText("Katları Dağıt");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(100, 130, 200, 100);

        jButton20.setText("Kart At");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(380, 130, 200, 100);

        jButton21.setText("Kart Al");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(660, 130, 200, 100);

        jLabel8.setBackground(new java.awt.Color(255, 102, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bilgisayar2");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1030, 90, 140, 60);

        jLabel7.setBackground(new java.awt.Color(255, 102, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bilgisayar1");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1030, 930, 140, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Bilgisayar2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1570, 350, 140, 100);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Bilgisayar1");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1300, 370, 140, 60);

        jLabel4.setBackground(new java.awt.Color(51, 51, 255));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1494, 380, 20, 350);

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1250, 380, 510, 340);

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1210, 360, 600, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arkaplan2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        pc1kartsayisi=3;
        pc2kartsayisi=3;
        jButton20.setVisible(true);
    int a =rand.nextInt(10);
    int b=rand.nextInt(10);
    int c=rand.nextInt(10);
    int d=rand.nextInt(10);
    int e=rand.nextInt(10);
    int f=rand.nextInt(10);
if(a==b || a==c || a==d || a==e|| a==f || b==c || b==d || b==e || b==f || c==d || c==e || c==f || d==e || d==f || f==e){
    while(a==b||a==c||a==d||a==e||a==f||b==c||b==d||b==e||b==f||c==d||c==e||c==f||d==e||d==f||f==e){
     a=rand.nextInt(10);
     b=rand.nextInt(10);
     c=rand.nextInt(10);
     d=rand.nextInt(10);
     e=rand.nextInt(10);
     f=rand.nextInt(10);
    }
}       jButton11.setVisible(true);
        jButton12.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        jButton19.setVisible(false);
        yerdekipokemonlar.set(a,999);
        yerdekipokemonlar.set(b,999);
        yerdekipokemonlar.set(c,999);
        yerdekipokemonlar.set(d,999);
        yerdekipokemonlar.set(e,999);
        yerdekipokemonlar.set(f,999);
        if(a==0){
           jButton11.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
           jButton1.setVisible(false);
           pcpokemonlar1.add(0);
        }
        if(a==1){
           jButton11.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            pcpokemonlar1.add(1);
        }
        if(a==2){
            jButton11.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             pcpokemonlar1.add(2);
        }
        if(a==3){
            jButton11.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             pcpokemonlar1.add(3);
        }
        if(a==4){
            jButton11.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             pcpokemonlar1.add(4);
        }
        if(a==5){
            jButton11.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             pcpokemonlar1.add(5);
        }
        if(a==6){
            jButton11.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             pcpokemonlar1.add(6);
        }
        if(a==7){
            jButton11.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             pcpokemonlar1.add(7);
        }
        if(a==8){
            jButton11.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             pcpokemonlar1.add(8);
        }
        if(a==9){
            jButton11.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             pcpokemonlar1.add(9);
        }
        if(b==0){
           jButton12.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            jButton1.setVisible(false);
            pcpokemonlar1.add(0);
        }
        if(b==1){
           jButton12.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            pcpokemonlar1.add(1);
        }
        if(b==2){
            jButton12.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             pcpokemonlar1.add(2);
        }
        if(b==3){
            jButton12.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             pcpokemonlar1.add(3);
        }
        if(b==4){
            jButton12.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             pcpokemonlar1.add(4);
        }
        if(b==5){
            jButton12.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             pcpokemonlar1.add(5);
        }
        if(b==6){
            jButton12.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             pcpokemonlar1.add(6);
        }
        if(b==7){
            jButton12.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             pcpokemonlar1.add(7);
        }
        if(b==8){
            jButton12.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             pcpokemonlar1.add(8);
        }
        if(b==9){
            jButton12.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             pcpokemonlar1.add(9);
        }
        if(c==0){
           jButton13.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            jButton1.setVisible(false);
            pcpokemonlar1.add(0);
        }
        if(c==1){
           jButton13.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            pcpokemonlar1.add(1);
        }
        if(c==2){
            jButton13.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             pcpokemonlar1.add(2);
        }
        if(c==3){
            jButton13.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             pcpokemonlar1.add(3);
        }
        if(c==4){
            jButton13.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             pcpokemonlar1.add(4);
        }
        if(c==5){
            jButton13.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             pcpokemonlar1.add(5);
        }
        if(c==6){
            jButton13.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             pcpokemonlar1.add(6);
        }
        if(c==7){
            jButton13.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             pcpokemonlar1.add(7);
        }
        if(c==8){
            jButton13.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             pcpokemonlar1.add(8);
        }
        if(c==9){
            jButton13.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             pcpokemonlar1.add(9);
        }
        if(d==0){
           jButton14.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
           jButton1.setVisible(false);
           pcpokemonlar2.add(0);
        }
        if(d==1){
           jButton14.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            pcpokemonlar2.add(1);
        }
        if(d==2){
            jButton14.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             pcpokemonlar2.add(2);
        }
        if(d==3){
            jButton14.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             pcpokemonlar2.add(3);
        }
        if(d==4){
            jButton14.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             pcpokemonlar2.add(4);
        }
        if(d==5){
            jButton14.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             pcpokemonlar2.add(5);
        }
        if(d==6){
            jButton14.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             pcpokemonlar2.add(6);
        }
        if(d==7){
            jButton14.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             pcpokemonlar2.add(7);
        }
        if(d==8){
            jButton14.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             pcpokemonlar2.add(8);
        }
        if(d==9){
            jButton14.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             pcpokemonlar2.add(9);
        }
        if(e==0){
           jButton15.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            jButton1.setVisible(false);
            pcpokemonlar2.add(0);
        }
        if(e==1){
           jButton15.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            pcpokemonlar2.add(1);
        }
        if(e==2){
            jButton15.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             pcpokemonlar2.add(2);
        }
        if(e==3){
            jButton15.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             pcpokemonlar2.add(3);
        }
        if(e==4){
            jButton15.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             pcpokemonlar2.add(4);
        }
        if(e==5){
            jButton15.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             pcpokemonlar2.add(5);
        }
        if(e==6){
            jButton15.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             pcpokemonlar2.add(6);
        }
        if(e==7){
            jButton15.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             pcpokemonlar2.add(7);
        }
        if(e==8){
            jButton15.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             pcpokemonlar2.add(8);
        }
        if(e==9){
            jButton15.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             pcpokemonlar2.add(9);
        }
        if(f==0){
           jButton16.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            jButton1.setVisible(false);
            pcpokemonlar2.add(0);
        }
        if(f==1){
           jButton16.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            pcpokemonlar2.add(1);
        }
        if(f==2){
            jButton16.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             pcpokemonlar2.add(2);
        }
        if(f==3){
            jButton16.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             pcpokemonlar2.add(3);
        }
        if(f==4){
            jButton16.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             pcpokemonlar2.add(4);
        }
        if(f==5){
            jButton16.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             pcpokemonlar2.add(5);
        }
        if(f==6){
            jButton16.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             pcpokemonlar2.add(6);
        }
        if(f==7){
            jButton16.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             pcpokemonlar2.add(7);
        }
        if(f==8){
            jButton16.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             pcpokemonlar2.add(8);
        }
        if(f==9){
            jButton16.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             pcpokemonlar2.add(9);
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        son++;
        x=rand.nextInt(3);
        y=rand.nextInt(3);
        if(kartsec!=2){
        jButton20.setVisible(false);
        jButton21.setVisible(true);}
        while(pcpokemonlar1.get(x)==999){
            x=rand.nextInt(3);
        }while(pcpokemonlar2.get(y)==999){
            y=rand.nextInt(3);
        }
        if(x==0){
            jButton11.setVisible(false);            
            pc1atılankart=1;
            if(pcpokemonlar1.get(0)==0){
                jButton17.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar1 = charmander.getHasarpuani();
                        }
            if(pcpokemonlar1.get(0)==1){
                jButton17.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar1 = butterfree.getHasarpuani();
                        }
            if(pcpokemonlar1.get(0)==2){
                jButton17.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar1 = bulbasaur.getHasarpuani();
                        }
            if(pcpokemonlar1.get(0)==3){
                jButton17.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar1 = jigglypuff.getHasarpuani();
                        }
            if(pcpokemonlar1.get(0)==4){
                jButton17.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar1 = meowth.getHasarpuani();
                        }
            if(pcpokemonlar1.get(0)==5){
                jButton17.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar1 = pikachu.getHasarpuani();
                        }
            if(pcpokemonlar1.get(0)==6){
                jButton17.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar1 = psyduck.getHasarpuani();
                        }
            if(pcpokemonlar1.get(0)==7){
                jButton17.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar1 = squirtle.getHasarpuani();
                        }
            if(pcpokemonlar1.get(0)==8){
                jButton17.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar1 = zubat.getHasarpuani();
                        }
            if(pcpokemonlar1.get(0)==9){
                jButton17.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar1 = snorlax.getHasarpuani();
                        }
            pcpokemonlar1.set(0,999);
        }
        if(x==1){
            jButton12.setVisible(false);           
            pc1atılankart=2;
            if(pcpokemonlar1.get(1)==0){
                jButton17.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar1 = charmander.getHasarpuani();
                        }
            if(pcpokemonlar1.get(1)==1){
                jButton17.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar1 = butterfree.getHasarpuani();
                        }
            if(pcpokemonlar1.get(1)==2){
                jButton17.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar1 = bulbasaur.getHasarpuani();
                        }
            if(pcpokemonlar1.get(1)==3){
                jButton17.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar1 = jigglypuff.getHasarpuani();
                        }
            if(pcpokemonlar1.get(1)==4){
                jButton17.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar1 = meowth.getHasarpuani();
                        }
            if(pcpokemonlar1.get(1)==5){
                jButton17.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar1 = pikachu.getHasarpuani();
                        }
            if(pcpokemonlar1.get(1)==6){
                jButton17.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar1 = psyduck.getHasarpuani();
                        }
            if(pcpokemonlar1.get(1)==7){
                jButton17.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar1 = squirtle.getHasarpuani();
                        }
            if(pcpokemonlar1.get(1)==8){
                jButton17.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar1 = zubat.getHasarpuani();
                        }
            if(pcpokemonlar1.get(1)==9){
                jButton17.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar1 = snorlax.getHasarpuani();
                        }
            pcpokemonlar1.set(1,999);
        }
        if(x==2){
            jButton13.setVisible(false);
            pc1atılankart=3;
            if(pcpokemonlar1.get(2)==0){
                jButton17.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar1 = charmander.getHasarpuani();
                        }
            if(pcpokemonlar1.get(2)==1){
                jButton17.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar1 = butterfree.getHasarpuani();
                        }
            if(pcpokemonlar1.get(2)==2){
                jButton17.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar1 = bulbasaur.getHasarpuani();
                        }
            if(pcpokemonlar1.get(2)==3){
                jButton17.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar1 = jigglypuff.getHasarpuani();
                        }
            if(pcpokemonlar1.get(2)==4){
                jButton17.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar1 = meowth.getHasarpuani();
                        }
            if(pcpokemonlar1.get(2)==5){
                jButton17.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar1 = pikachu.getHasarpuani();
                        }
            if(pcpokemonlar1.get(2)==6){
                jButton17.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar1 = psyduck.getHasarpuani();
                        }
            if(pcpokemonlar1.get(2)==7){
                jButton17.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar1 = squirtle.getHasarpuani();
                        }
            if(pcpokemonlar1.get(2)==8){
                jButton17.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar1 = zubat.getHasarpuani();
                        }
            if(pcpokemonlar1.get(2)==9){
                jButton17.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar1 = snorlax.getHasarpuani();
                        }
            pcpokemonlar1.set(2,999);
        }
        if(y==0){
            jButton14.setVisible(false);
            pc2atılankart=1;
            if(pcpokemonlar2.get(0)==0){
                jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
                        }
            if(pcpokemonlar2.get(0)==1){
                jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
                        }
            if(pcpokemonlar2.get(0)==2){
                jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                        }
            if(pcpokemonlar2.get(0)==3){
                jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
                        }
            if(pcpokemonlar2.get(0)==4){
                jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2= meowth.getHasarpuani();
                        }
            if(pcpokemonlar2.get(0)==5){
                jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
                        }
            if(pcpokemonlar2.get(0)==6){
                jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
                        }
            if(pcpokemonlar2.get(0)==7){
                jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2 = squirtle.getHasarpuani();
                        }
            if(pcpokemonlar2.get(0)==8){
                jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2= zubat.getHasarpuani();
                        }
            if(pcpokemonlar2.get(0)==9){
                jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2 = snorlax.getHasarpuani();
                        }
            pcpokemonlar2.set(0,999);
        }
        if(y==1){
            jButton15.setVisible(false);          
            pc2atılankart=2;
            if(pcpokemonlar2.get(1)==0){
                jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
                        }
            if(pcpokemonlar2.get(1)==1){
                jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
                        }
            if(pcpokemonlar2.get(1)==2){
                jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                        }
            if(pcpokemonlar2.get(1)==3){
                jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
                        }
            if(pcpokemonlar2.get(1)==4){
                jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2= meowth.getHasarpuani();
                        }
            if(pcpokemonlar2.get(1)==5){
                jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
                        }
            if(pcpokemonlar2.get(1)==6){
                jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
                        }
            if(pcpokemonlar2.get(1)==7){
                jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2 = squirtle.getHasarpuani();
                        }
            if(pcpokemonlar2.get(1)==8){
                jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2= zubat.getHasarpuani();
                        }
            if(pcpokemonlar2.get(1)==9){
                jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2 = snorlax.getHasarpuani();
                        }
            pcpokemonlar2.set(1,999);
        }
        if(y==2){
            jButton16.setVisible(false);
            pc2atılankart=3;
            if(pcpokemonlar2.get(2)==0){
                jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
                        }
            if(pcpokemonlar2.get(2)==1){
                jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
                        }
            if(pcpokemonlar2.get(2)==2){
                jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                        }
            if(pcpokemonlar2.get(2)==3){
                jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
                        }
            if(pcpokemonlar2.get(2)==4){
                jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2= meowth.getHasarpuani();
                        }
            if(pcpokemonlar2.get(2)==5){
                jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
                        }
            if(pcpokemonlar2.get(2)==6){
                jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
                        }
            if(pcpokemonlar2.get(2)==7){
                jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2 = squirtle.getHasarpuani();
                        }
            if(pcpokemonlar2.get(2)==8){
                jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2= zubat.getHasarpuani();
                        }
            if(pcpokemonlar2.get(2)==9){
                jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2 = snorlax.getHasarpuani();
                        }
            pcpokemonlar2.set(2,999);
        }
        if(hasar1>hasar2){
            bilg1skor=bilg1skor+5;
        }
        if(hasar2>hasar1){
            bilg2skor=bilg2skor+5;
        }
        if(son==5){
            if(bilg1skor>bilg2skor){
            JOptionPane.showMessageDialog(null, "Oyun Bitti Bilgisayar1 Kazandı! \n Bilgisayar1:"+bilg1skor+"\n Bilgisayar2:"+bilg2skor);
            dispose();}
            if(bilg1skor<bilg2skor){
            JOptionPane.showMessageDialog(null, "Oyun Bitti Bilgisayar2 Kazandı! \n Bilgisayar2:"+bilg1skor+"\n Bilgisayar2:"+bilg2skor);
            dispose();}
            if(bilg1skor==bilg2skor){
                JOptionPane.showMessageDialog(null,"Oyun Bitti Berabere! \n Bilgisayar2:"+bilg1skor+"\n Bilgisayar2:"+bilg2skor);
            dispose();
            }
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
       jButton21.setVisible(false);
       jButton20.setVisible(true);
       kartsec++;
        x=rand.nextInt(10);
        y=rand.nextInt(10);
        while(yerdekipokemonlar.get(x)==999){
            x=rand.nextInt(10);
        }
        while(yerdekipokemonlar.get(y)==999||x==y){
            y=rand.nextInt(10);
        }
        
            if(pc1atılankart==1){
                jButton11.setVisible(true);
                if(yerdekipokemonlar.get(x)==0){
                    pcpokemonlar1.set(0,0);
                      jButton11.setIcon(new javax.swing.ImageIcon(charmander.getImage())); 
                      jButton1.setVisible(false);
                      
                }
                if(yerdekipokemonlar.get(x)==1){
                    pcpokemonlar1.set(0,1);
                      jButton11.setIcon(new javax.swing.ImageIcon(butterfree.getImage())); 
                      jButton2.setVisible(false);
                     
                }
                if(yerdekipokemonlar.get(x)==2){
                    pcpokemonlar1.set(0,2);
                      jButton11.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage())); 
                      jButton3.setVisible(false);
                      
                }
                if(yerdekipokemonlar.get(x)==3){
                    pcpokemonlar1.set(0,3);
                      jButton11.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage())); 
                      jButton4.setVisible(false);
                      
                }
                if(yerdekipokemonlar.get(x)==4){
                    pcpokemonlar1.set(0,4);
                      jButton11.setIcon(new javax.swing.ImageIcon(meowth.getImage())); 
                      jButton5.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==5){
                    pcpokemonlar1.set(0,5);
                      jButton11.setIcon(new javax.swing.ImageIcon(pikachu.getImage())); 
                      jButton6.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==6){
                    pcpokemonlar1.set(0,6);
                      jButton11.setIcon(new javax.swing.ImageIcon(psyduck.getImage())); 
                      jButton7.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==7){
                    pcpokemonlar1.set(0,7);
                      jButton11.setIcon(new javax.swing.ImageIcon(squirtle.getImage())); 
                      jButton8.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==8){
                    pcpokemonlar1.set(0,8);
                      jButton11.setIcon(new javax.swing.ImageIcon(zubat.getImage())); 
                      jButton9.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==9){
                    pcpokemonlar1.set(0,9);
                      jButton11.setIcon(new javax.swing.ImageIcon(snorlax.getImage())); 
                      jButton10.setVisible(false);
                }
            }
            if(pc1atılankart==2){
                jButton12.setVisible(true);
                if(yerdekipokemonlar.get(x)==0){
                    pcpokemonlar1.set(1,0);
                      jButton12.setIcon(new javax.swing.ImageIcon(charmander.getImage())); 
                      jButton1.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==1){
                    pcpokemonlar1.set(1,1);
                      jButton12.setIcon(new javax.swing.ImageIcon(butterfree.getImage())); 
                      jButton2.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==2){
                    pcpokemonlar1.set(1,2);
                      jButton12.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage())); 
                      jButton3.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==3){
                    pcpokemonlar1.set(1,3);
                      jButton12.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage())); 
                      jButton4.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==4){
                    pcpokemonlar1.set(1,4);
                      jButton12.setIcon(new javax.swing.ImageIcon(meowth.getImage())); 
                      jButton5.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==5){
                    pcpokemonlar1.set(1,5);
                      jButton12.setIcon(new javax.swing.ImageIcon(pikachu.getImage())); 
                      jButton6.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==6){
                    pcpokemonlar1.set(1,6);
                      jButton12.setIcon(new javax.swing.ImageIcon(psyduck.getImage())); 
                      jButton7.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==7){
                    pcpokemonlar1.set(1,7);
                      jButton12.setIcon(new javax.swing.ImageIcon(squirtle.getImage())); 
                      jButton8.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==8){
                    pcpokemonlar1.set(1,8);
                      jButton12.setIcon(new javax.swing.ImageIcon(zubat.getImage())); 
                      jButton9.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==9){
                    pcpokemonlar1.set(1,9);
                      jButton12.setIcon(new javax.swing.ImageIcon(snorlax.getImage())); 
                      jButton10.setVisible(false);
                }
            }
            if(pc1atılankart==3){
                jButton13.setVisible(true);
                if(yerdekipokemonlar.get(x)==0){
                    pcpokemonlar1.set(2,0);
                      jButton13.setIcon(new javax.swing.ImageIcon(charmander.getImage())); 
                      jButton1.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==1){
                    pcpokemonlar1.set(2,1);
                      jButton13.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
                      jButton2.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==2){
                    pcpokemonlar1.set(2,2);
                      jButton13.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage())); 
                      jButton3.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==3){
                    pcpokemonlar1.set(2,3);
                      jButton13.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage())); 
                      jButton4.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==4){
                    pcpokemonlar1.set(2,4);
                      jButton13.setIcon(new javax.swing.ImageIcon(meowth.getImage())); 
                      jButton5.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==5){
                    pcpokemonlar1.set(2,5);
                      jButton13.setIcon(new javax.swing.ImageIcon(pikachu.getImage())); 
                      jButton6.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==6){
                    pcpokemonlar1.set(2,6);
                      jButton11.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
                      jButton7.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==7){
                    pcpokemonlar1.set(2,7);
                      jButton13.setIcon(new javax.swing.ImageIcon(squirtle.getImage())); 
                      jButton8.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==8){
                    pcpokemonlar1.set(2,8);
                      jButton13.setIcon(new javax.swing.ImageIcon(zubat.getImage())); 
                      jButton9.setVisible(false);
                }
                if(yerdekipokemonlar.get(x)==9){
                    pcpokemonlar1.set(2,9);
                      jButton13.setIcon(new javax.swing.ImageIcon(snorlax.getImage())); 
                      jButton10.setVisible(false);
                }
            
        
            }
            if(pc2atılankart==1){
                jButton14.setVisible(true);
                if(yerdekipokemonlar.get(y)==0){
                    pcpokemonlar2.set(0,0);
                      jButton14.setIcon(new javax.swing.ImageIcon(charmander.getImage())); 
                      jButton1.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==1){
                    pcpokemonlar2.set(0,1);
                      jButton14.setIcon(new javax.swing.ImageIcon(butterfree.getImage())); 
                      jButton2.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==2){
                    pcpokemonlar2.set(0,2);
                      jButton14.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage())); 
                      jButton3.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==3){
                    pcpokemonlar2.set(0,3);
                      jButton14.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage())); 
                      jButton4.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==4){
                    pcpokemonlar2.set(0,4);
                      jButton14.setIcon(new javax.swing.ImageIcon(meowth.getImage())); 
                      jButton5.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==5){
                    pcpokemonlar2.set(0,5);
                      jButton14.setIcon(new javax.swing.ImageIcon(pikachu.getImage())); 
                      jButton6.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==6){
                    pcpokemonlar2.set(0,6);
                      jButton14.setIcon(new javax.swing.ImageIcon(psyduck.getImage())); 
                      jButton7.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==7){
                    pcpokemonlar2.set(0,7);
                      jButton14.setIcon(new javax.swing.ImageIcon(squirtle.getImage())); 
                      jButton8.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==8){
                    pcpokemonlar2.set(0,8);
                      jButton14.setIcon(new javax.swing.ImageIcon(zubat.getImage())); 
                      jButton9.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==9){
                    pcpokemonlar2.set(0,9);
                      jButton14.setIcon(new javax.swing.ImageIcon(snorlax.getImage())); 
                      jButton10.setVisible(false);
                }
            }
            if(pc2atılankart==2){
                jButton15.setVisible(true);
                if(yerdekipokemonlar.get(y)==0){
                    pcpokemonlar2.set(1,0);
                      jButton15.setIcon(new javax.swing.ImageIcon(charmander.getImage())); 
                      jButton1.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==1){
                    pcpokemonlar2.set(1,1);
                      jButton15.setIcon(new javax.swing.ImageIcon(butterfree.getImage())); 
                      jButton2.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==2){
                    pcpokemonlar2.set(1,2);
                      jButton15.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage())); 
                      jButton3.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==3){
                    pcpokemonlar2.set(1,3);
                      jButton15.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage())); 
                      jButton4.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==4){
                    pcpokemonlar2.set(1,4);
                      jButton15.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
                      jButton5.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==5){
                    pcpokemonlar2.set(1,5);
                      jButton15.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
                      jButton6.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==6){
                    pcpokemonlar2.set(1,6);
                      jButton15.setIcon(new javax.swing.ImageIcon(psyduck.getImage())); 
                      jButton7.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==7){
                    pcpokemonlar2.set(1,7);
                      jButton15.setIcon(new javax.swing.ImageIcon(squirtle.getImage())); 
                      jButton8.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==8){
                    pcpokemonlar2.set(1,8);
                      jButton15.setIcon(new javax.swing.ImageIcon(zubat.getImage())); 
                      jButton9.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==9){
                    pcpokemonlar2.set(1,9);
                      jButton15.setIcon(new javax.swing.ImageIcon(snorlax.getImage())); 
                      jButton10.setVisible(false);
                }
            }
            if(pc2atılankart==3){
                jButton16.setVisible(true);
                if(yerdekipokemonlar.get(y)==0){
                    pcpokemonlar2.set(2,0);
                      jButton16.setIcon(new javax.swing.ImageIcon(charmander.getImage())); 
                      jButton1.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==1){
                    pcpokemonlar2.set(2,1);
                      jButton16.setIcon(new javax.swing.ImageIcon(butterfree.getImage())); 
                      jButton2.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==2){
                    pcpokemonlar2.set(2,2);
                      jButton16.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage())); 
                      jButton3.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==3){
                    pcpokemonlar2.set(2,3);
                      jButton16.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage())); 
                      jButton4.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==4){
                    pcpokemonlar2.set(2,4);
                      jButton16.setIcon(new javax.swing.ImageIcon(meowth.getImage())); 
                      jButton5.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==5){
                    pcpokemonlar2.set(2,5);
                      jButton16.setIcon(new javax.swing.ImageIcon(pikachu.getImage())); 
                      jButton6.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==6){
                    pcpokemonlar2.set(2,6);
                      jButton16.setIcon(new javax.swing.ImageIcon(psyduck.getImage())); 
                      jButton7.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==7){
                    pcpokemonlar2.set(2,7);
                      jButton16.setIcon(new javax.swing.ImageIcon(squirtle.getImage())); 
                      jButton8.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==8){
                    pcpokemonlar2.set(2,8);
                      jButton16.setIcon(new javax.swing.ImageIcon(zubat.getImage())); 
                      jButton9.setVisible(false);
                }
                if(yerdekipokemonlar.get(y)==9){
                    pcpokemonlar2.set(2,9);
                      jButton16.setIcon(new javax.swing.ImageIcon(snorlax.getImage())); 
                      jButton10.setVisible(false);
                }
            }
        yerdekipokemonlar.set(x,999);
        yerdekipokemonlar.set(y,999);
    }//GEN-LAST:event_jButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bilgisayarvsbilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bilgisayarvsbilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bilgisayarvsbilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bilgisayarvsbilgisayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bilgisayarvsbilgisayar().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
