
package javaapplication1;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.*;
/**
 *
 * @author bayram
 */
public class Playervspc extends javax.swing.JFrame {
    int atılankart,pcatılankart;
    int ortadakibuton;
    int hasarpuani;
    int kartsayisi=0,pckartsayisi,kartsec=0,pckart=0;
    int x,y,son=0;
    int bilgskor=0,oyuncuskor=0;
    charmander charmander=new charmander();
    Pokemon pokemon1=charmander;
    butterfree butterfree=new butterfree();
    Pokemon pokemon2=butterfree;
    jigglypuff jigglypuff=new jigglypuff();
    Pokemon pokemon3=jigglypuff;
    bulbasaur bulbasaur=new bulbasaur();
    Pokemon pokemon4=bulbasaur;
    meowth meowth=new meowth();
    Pokemon pokemon5=meowth;
    pikachu pikachu=new pikachu();
    Pokemon pokemon6=pikachu;
    psyduck psyduck=new psyduck();
    Pokemon pokemon7=psyduck;
    squirtle squirtle=new squirtle();
    Pokemon pokemon8=squirtle;
    zubat zubat=new zubat();
    Pokemon pokemon9=zubat;
    snorlax snorlax=new snorlax();
    Pokemon pokemon10=snorlax;
    ArrayList<Integer> yerdekipokemonlar=new ArrayList<>();
    ArrayList<Integer> oyuncupokemonlar=new ArrayList<>();
    ArrayList<Integer> pcpokemonlar=new ArrayList<>();
    static int hasar1,hasar2;
    Random rand = new Random();
    
    
       

  

    
    

    /**
     * Creates new form PlayervsPlayer
     */
    
    public Playervspc() {
//        this.pikachu = new Pokemon();
     //   this.<error> = b /*&& a==c /*a==d|| a==e||a==f||b==c||b==d||b==e||b==f||c==d||c==e||c==f||d==e||d==f||f==e*/;
        initComponents();
        
       
        jButton16.setVisible(false);
        jButton15.setVisible(false);
        jButton14.setVisible(false);
        jButton13.setVisible(false);
        jButton12.setVisible(false);
        jButton11.setVisible(false);
        for (int i = 0; i <10; i++) {
           yerdekipokemonlar.add(i);           
        }
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("POKEMON");
        setPreferredSize(new java.awt.Dimension(2920, 2080));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/charmander.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 320, 200, 280);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/butterfree.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 320, 200, 280);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bulbasaur.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 320, 200, 280);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jigglypuff.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(640, 320, 200, 280);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/meowth.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(840, 320, 200, 280);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pikachu.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(40, 600, 200, 280);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/psyduck.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(240, 600, 200, 280);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/squirtle.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(440, 600, 200, 280);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/zubat.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(640, 600, 200, 280);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/snorlax.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(840, 600, 200, 280);

        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(1210, 790, 200, 280);

        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(1420, 790, 200, 280);

        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(1630, 790, 200, 280);
        getContentPane().add(jButton14);
        jButton14.setBounds(1220, 10, 200, 280);
        getContentPane().add(jButton15);
        jButton15.setBounds(1430, 10, 200, 280);
        getContentPane().add(jButton16);
        jButton16.setBounds(1640, 10, 200, 280);
        getContentPane().add(jButton17);
        jButton17.setBounds(1270, 420, 200, 280);
        getContentPane().add(jButton18);
        jButton18.setBounds(1540, 420, 200, 280);

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton19.setText("Kartları Dağıt");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(90, 70, 190, 80);

        jLabel8.setBackground(new java.awt.Color(255, 102, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(""+insanoyuncusu.getOyuncuadi());
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1030, 930, 140, 60);

        jLabel7.setBackground(new java.awt.Color(255, 102, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bilgisayar");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1030, 110, 140, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Bilgisayar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1580, 350, 200, 100);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Oyuncu");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1320, 380, 100, 40);

        jLabel6.setBackground(new java.awt.Color(0, 0, 204));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1490, 360, 30, 360);

        jLabel5.setBackground(new java.awt.Color(255, 51, 51));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1250, 380, 510, 340);

        jLabel4.setBackground(new java.awt.Color(0, 0, 153));
        jLabel4.setForeground(new java.awt.Color(255, 51, 204));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1210, 360, 600, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arkaplan2.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        kartsayisi=3;
        pckart=3;
    
    int a =rand.nextInt(10);
    int b=rand.nextInt(10);
    int c=rand.nextInt(10);
    int d=rand.nextInt(10);
    int e=rand.nextInt(10);
    int f=rand.nextInt(10);
if(a==b || a==c || a==d || a==e|| a==f || b==c || b==d || b==e || b==f || c==d || c==e || c==f || d==e || d==f || f==e){
    while(a==b||a==c||a==d||a==e||a==f||b==c||b==d||b==e||b==f||c==d||c==e||c==f||d==e||d==f||f==e){
     a=rand.nextInt(10);
     b=rand.nextInt(10);
     c=rand.nextInt(10);
     d=rand.nextInt(10);
     e=rand.nextInt(10);
     f=rand.nextInt(10);
    }
}       jButton11.setVisible(true);
        jButton12.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        jButton19.setVisible(false);
        yerdekipokemonlar.set(a,999);
        yerdekipokemonlar.set(b,999);
        yerdekipokemonlar.set(c,999);
        yerdekipokemonlar.set(d,999);
        yerdekipokemonlar.set(e,999);
        yerdekipokemonlar.set(f,999);
        if(a==0){
           jButton11.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
           jButton1.setVisible(false);
           oyuncupokemonlar.add(0);
        }
        if(a==1){
           jButton11.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            oyuncupokemonlar.add(1);
        }
        if(a==2){
            jButton11.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             oyuncupokemonlar.add(2);
        }
        if(a==3){
            jButton11.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             oyuncupokemonlar.add(3);
        }
        if(a==4){
            jButton11.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             oyuncupokemonlar.add(4);
        }
        if(a==5){
            jButton11.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             oyuncupokemonlar.add(5);
        }
        if(a==6){
            jButton11.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             oyuncupokemonlar.add(6);
        }
        if(a==7){
            jButton11.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             oyuncupokemonlar.add(7);
        }
        if(a==8){
            jButton11.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             oyuncupokemonlar.add(8);
        }
        if(a==9){
            jButton11.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             oyuncupokemonlar.add(9);
        }
        if(b==0){
           jButton12.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            jButton1.setVisible(false);
            oyuncupokemonlar.add(0);
        }
        if(b==1){
           jButton12.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            oyuncupokemonlar.add(1);
        }
        if(b==2){
            jButton12.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             oyuncupokemonlar.add(2);
        }
        if(b==3){
            jButton12.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             oyuncupokemonlar.add(3);
        }
        if(b==4){
            jButton12.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             oyuncupokemonlar.add(4);
        }
        if(b==5){
            jButton12.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             oyuncupokemonlar.add(5);
        }
        if(b==6){
            jButton12.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             oyuncupokemonlar.add(6);
        }
        if(b==7){
            jButton12.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             oyuncupokemonlar.add(7);
        }
        if(b==8){
            jButton12.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             oyuncupokemonlar.add(8);
        }
        if(b==9){
            jButton12.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             oyuncupokemonlar.add(9);
        }
        if(c==0){
           jButton13.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            jButton1.setVisible(false);
            oyuncupokemonlar.add(0);
        }
        if(c==1){
           jButton13.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            oyuncupokemonlar.add(1);
        }
        if(c==2){
            jButton13.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             oyuncupokemonlar.add(2);
        }
        if(c==3){
            jButton13.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             oyuncupokemonlar.add(3);
        }
        if(c==4){
            jButton13.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             oyuncupokemonlar.add(4);
        }
        if(c==5){
            jButton13.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             oyuncupokemonlar.add(5);
        }
        if(c==6){
            jButton13.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             oyuncupokemonlar.add(6);
        }
        if(c==7){
            jButton13.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             oyuncupokemonlar.add(7);
        }
        if(c==8){
            jButton13.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             oyuncupokemonlar.add(8);
        }
        if(c==9){
            jButton13.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             oyuncupokemonlar.add(9);
        }
        if(d==0){
           jButton14.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
           jButton1.setVisible(false);
           pcpokemonlar.add(0);
        }
        if(d==1){
           jButton14.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            pcpokemonlar.add(1);
        }
        if(d==2){
            jButton14.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             pcpokemonlar.add(2);
        }
        if(d==3){
            jButton14.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             pcpokemonlar.add(3);
        }
        if(d==4){
            jButton14.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             pcpokemonlar.add(4);
        }
        if(d==5){
            jButton14.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             pcpokemonlar.add(5);
        }
        if(d==6){
            jButton14.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             pcpokemonlar.add(6);
        }
        if(d==7){
            jButton14.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             pcpokemonlar.add(7);
        }
        if(d==8){
            jButton14.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             pcpokemonlar.add(8);
        }
        if(d==9){
            jButton14.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             pcpokemonlar.add(9);
        }
        if(e==0){
           jButton15.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            jButton1.setVisible(false);
            pcpokemonlar.add(0);
        }
        if(e==1){
           jButton15.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            pcpokemonlar.add(1);
        }
        if(e==2){
            jButton15.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             pcpokemonlar.add(2);
        }
        if(e==3){
            jButton15.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             pcpokemonlar.add(3);
        }
        if(e==4){
            jButton15.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             pcpokemonlar.add(4);
        }
        if(e==5){
            jButton15.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             pcpokemonlar.add(5);
        }
        if(e==6){
            jButton15.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             pcpokemonlar.add(6);
        }
        if(e==7){
            jButton15.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             pcpokemonlar.add(7);
        }
        if(e==8){
            jButton15.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             pcpokemonlar.add(8);
        }
        if(e==9){
            jButton15.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             pcpokemonlar.add(9);
        }
        if(f==0){
           jButton16.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            jButton1.setVisible(false);
            pcpokemonlar.add(0);
        }
        if(f==1){
           jButton16.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            jButton2.setVisible(false);
            pcpokemonlar.add(1);
        }
        if(f==2){
            jButton16.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
             jButton3.setVisible(false);
             pcpokemonlar.add(2);
        }
        if(f==3){
            jButton16.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
             jButton4.setVisible(false);
             pcpokemonlar.add(3);
        }
        if(f==4){
            jButton16.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
             jButton5.setVisible(false);
             pcpokemonlar.add(4);
        }
        if(f==5){
            jButton16.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
             jButton6.setVisible(false);
             pcpokemonlar.add(5);
        }
        if(f==6){
            jButton16.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
             jButton7.setVisible(false);
             pcpokemonlar.add(6);
        }
        if(f==7){
            jButton16.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
             jButton8.setVisible(false);
             pcpokemonlar.add(7);
        }
        if(f==8){
            jButton16.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
             jButton9.setVisible(false);
             pcpokemonlar.add(8);
        }
        if(f==9){
            jButton16.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
             jButton10.setVisible(false);
             pcpokemonlar.add(9);
        }
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        
        if(kartsec==2){
            kartsayisi=3;
        }     
        if(kartsayisi>2){
            son++;
            kartsayisi--;
          atılankart=2;
          jButton12.setVisible(false);
        if(oyuncupokemonlar.get(1)==0){
        jButton17.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar1 = charmander.getHasarpuani();
           oyuncupokemonlar.set(1,999);
        }
        if(oyuncupokemonlar.get(1)==1){
        jButton17.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar1 = butterfree.getHasarpuani();
            oyuncupokemonlar.set(1,999);
        }
        if(oyuncupokemonlar.get(1)==2){
        jButton17.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar1 = bulbasaur.getHasarpuani();
            oyuncupokemonlar.set(1,999);
        }
        if(oyuncupokemonlar.get(1)==3){
        jButton17.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar1 = jigglypuff.getHasarpuani();
            oyuncupokemonlar.set(1,999);
        }
        if(oyuncupokemonlar.get(1)==4){
        jButton17.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar1 = meowth.getHasarpuani();
            oyuncupokemonlar.set(1,999);
        }
        if(oyuncupokemonlar.get(1)==5){
        jButton17.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar1 = pikachu.getHasarpuani();
            oyuncupokemonlar.set(1,999);
        }
        if(oyuncupokemonlar.get(1)==6){
        jButton17.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar1 = psyduck.getHasarpuani();
            oyuncupokemonlar.set(1,999);
        }
        if(oyuncupokemonlar.get(1)==7){
        jButton17.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar1 = squirtle.getHasarpuani();
            oyuncupokemonlar.set(1,999);
        }
        if(oyuncupokemonlar.get(1)==8){
        jButton17.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar1 = zubat.getHasarpuani();
            oyuncupokemonlar.set(1,999);
        }
        if(oyuncupokemonlar.get(1)==9){
        jButton17.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar1 = snorlax.getHasarpuani();
            oyuncupokemonlar.set(1,999);
        }
        
        x=rand.nextInt(3);
        while(pcpokemonlar.get(x)==999){
            x=rand.nextInt(3);
        }
         
         if(x==0){
             jButton14.setVisible(false);
             pcatılankart=1;
             if(pcpokemonlar.get(0)==0){
        jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==1){
        jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
           pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==2){
        jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                    pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==3){
        jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==4){
        jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2 = meowth.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==5){
        jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==6){
        jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==7){
        jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2= squirtle.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==8){
        jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2 = zubat.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==9){
        jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2= snorlax.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
         }
         if(x==1){
             jButton15.setVisible(false);
             pcatılankart=2;
             if(pcpokemonlar.get(1)==0){
        jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==1){
        jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
           pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==2){
        jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                    pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==3){
        jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==4){
        jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2 = meowth.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==5){
        jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==6){
        jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==7){
        jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2= squirtle.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==8){
        jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2 = zubat.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==9){
        jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2= snorlax.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
         }
         if(x==2){
             jButton16.setVisible(false);
             pcatılankart=3;
             if(pcpokemonlar.get(2)==0){
        jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==1){
        jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
           pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==2){
        jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                    pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==3){
        jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==4){
        jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2 = meowth.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==5){
        jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==6){
        jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==7){
        jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2= squirtle.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==8){
        jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2 = zubat.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==9){
        jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2= snorlax.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
         }
         if(yerdekipokemonlar.get(0)!=999 || yerdekipokemonlar.get(1)!=999 || yerdekipokemonlar.get(2)!=999 || yerdekipokemonlar.get(3)!=999 || yerdekipokemonlar.get(4)!=999 || yerdekipokemonlar.get(5)!=999 || yerdekipokemonlar.get(6)!=999 || yerdekipokemonlar.get(7)!=999 || yerdekipokemonlar.get(8)!=999 || yerdekipokemonlar.get(9)!=999){
         y=rand.nextInt(10);        
         while( y!=yerdekipokemonlar.get(0) && y!=yerdekipokemonlar.get(1) && y!=yerdekipokemonlar.get(2)&&y!=yerdekipokemonlar.get(3)&&y!=yerdekipokemonlar.get(4)&&y!=yerdekipokemonlar.get(5)&&y!=yerdekipokemonlar.get(6)&&y!=yerdekipokemonlar.get(7)&&y!=yerdekipokemonlar.get(8)&&y!=yerdekipokemonlar.get(9))
         {
             y=rand.nextInt(10);
         }
         if(pcatılankart==1) {
              jButton14.setVisible(true);
             if(y==0){
         jButton14.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
         pcpokemonlar.set(0,0);
         yerdekipokemonlar.set(0,999);
         jButton1.setVisible(false);
             }
             if(y==1){
         jButton14.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
         pcpokemonlar.set(0,1);
         yerdekipokemonlar.set(1,999);
         jButton2.setVisible(false);
             }
             if(y==2){
         jButton14.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
         pcpokemonlar.set(0,2);
         yerdekipokemonlar.set(2,999);
         jButton3.setVisible(false);
             }
             if(y==3){
         jButton14.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
         pcpokemonlar.set(0,3);
         yerdekipokemonlar.set(3,999);
         jButton4.setVisible(false);
             }
             if(y==4){
         jButton14.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
         pcpokemonlar.set(0,4);
         yerdekipokemonlar.set(4,999);
         jButton5.setVisible(false);
             }
             if(y==5){
         jButton14.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
         pcpokemonlar.set(0,5);
         yerdekipokemonlar.set(5,999);
         jButton6.setVisible(false);
             }
             if(y==6){
         jButton14.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
         pcpokemonlar.set(0,6);
         yerdekipokemonlar.set(6,999);
         jButton7.setVisible(false);
             }
             if(y==7){
         jButton14.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
         pcpokemonlar.set(0,7);
         yerdekipokemonlar.set(7,999);
         jButton8.setVisible(false);
             }
             if(y==8){
         jButton14.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
         pcpokemonlar.set(0,8);
         yerdekipokemonlar.set(8,999);
         jButton9.setVisible(false);
             }
             if(y==9){
         jButton14.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
         pcpokemonlar.set(0,9);
         yerdekipokemonlar.set(9,999);
         jButton10.setVisible(false);
             }
             
         }
         if(pcatılankart==2) {
              jButton15.setVisible(true);
             if(y==0){
         jButton15.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
         pcpokemonlar.set(1,0);
         yerdekipokemonlar.set(0,999);
         jButton1.setVisible(false);
             }
             if(y==1){
         jButton15.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
         pcpokemonlar.set(1,1);
         yerdekipokemonlar.set(1,999);
         jButton2.setVisible(false);
             }
             if(y==2){
         jButton15.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
         pcpokemonlar.set(1,2);
         yerdekipokemonlar.set(2,999);
         jButton3.setVisible(false);
             }
             if(y==3){
         jButton15.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
         pcpokemonlar.set(1,3);
         yerdekipokemonlar.set(3,999);
         jButton4.setVisible(false);
             }
             if(y==4){
         jButton15.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
         pcpokemonlar.set(1,4);
         yerdekipokemonlar.set(4,999);
         jButton5.setVisible(false);
             }
             if(y==5){
         jButton15.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
         pcpokemonlar.set(1,5);
         yerdekipokemonlar.set(5,999);
         jButton6.setVisible(false);
             }
             if(y==6){
         jButton15.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
         pcpokemonlar.set(1,6);
         yerdekipokemonlar.set(6,999);
         jButton7.setVisible(false);
             }
             if(y==7){
         jButton15.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
         pcpokemonlar.set(1,7);
         yerdekipokemonlar.set(7,999);
         jButton8.setVisible(false);
             }
             if(y==8){
         jButton15.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
         pcpokemonlar.set(1,8);
         yerdekipokemonlar.set(8,999);
         jButton9.setVisible(false);
             }
             if(y==9){
         jButton15.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
         pcpokemonlar.set(1,9);
         yerdekipokemonlar.set(9,999);
         jButton10.setVisible(false);
             }
             
         }
         if(pcatılankart==3) {
             jButton16.setVisible(true);
             if(y==0){
         jButton16.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
         pcpokemonlar.set(2,0);
         yerdekipokemonlar.set(0,999);
         jButton1.setVisible(false);
             }
             if(y==1){
         jButton16.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
         pcpokemonlar.set(2,1);
         yerdekipokemonlar.set(1,999);
         jButton2.setVisible(false);
             }
             if(y==2){
         jButton16.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
         pcpokemonlar.set(2,2);
         yerdekipokemonlar.set(2,999);
         jButton3.setVisible(false);
             }
             if(y==3){
         jButton16.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
         pcpokemonlar.set(2,3);
         yerdekipokemonlar.set(3,999);
         jButton4.setVisible(false);
             }
             if(y==4){
         jButton16.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
         pcpokemonlar.set(2,4);
         yerdekipokemonlar.set(4,999);
         jButton5.setVisible(false);
             }
             if(y==5){
         jButton16.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
         pcpokemonlar.set(2,5);
         yerdekipokemonlar.set(5,999);
         jButton6.setVisible(false);
             }
             if(y==6){
         jButton16.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
         pcpokemonlar.set(2,6);
         yerdekipokemonlar.set(6,999);
         jButton7.setVisible(false);
             }
             if(y==7){
         jButton16.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
         pcpokemonlar.set(2,7);
         yerdekipokemonlar.set(7,999);
         jButton8.setVisible(false);
             }
             if(y==8){
         jButton16.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
         pcpokemonlar.set(2,8);
         yerdekipokemonlar.set(8,999);
         jButton9.setVisible(false);
             }
             if(y==9){
         jButton16.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
         pcpokemonlar.set(2,9);
         yerdekipokemonlar.set(9,999);
         jButton10.setVisible(false);
             }
             
         }}
        if(hasar1>hasar2){
            oyuncuskor=oyuncuskor+5;
            System.out.println(""+hasar1+hasar2);
        }
        if(hasar2>hasar1){
            bilgskor=bilgskor+5;
            System.out.println(""+hasar1+hasar2);           
        }
        if(son==5){
            if(bilgskor>=oyuncuskor){
            JOptionPane.showMessageDialog(null, "Oyun Bitti Bilgisayar Kazandı! \n Bilgisayar:"+bilgskor+"\n Oyuncu:"+oyuncuskor);
            dispose();}
            if(bilgskor<=oyuncuskor){
            JOptionPane.showMessageDialog(null, "Oyun Bitti "+insanoyuncusu.getOyuncuadi()+" Kazandı! \n Bilgisayar:"+bilgskor+"\n "+insanoyuncusu.getOyuncuadi()+oyuncuskor);
            dispose();}
        if(bilgskor==oyuncuskor){
                JOptionPane.showMessageDialog(null,"Oyun Bitti Berabere!");
                dispose();
            }
        }
        }
        System.out.println(""+oyuncuskor+bilgskor+son);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
        
        if(kartsec==2){
            kartsayisi=3;
        }  
        if(kartsayisi>2||(oyuncupokemonlar.get(0)!=999&&oyuncupokemonlar.get(1)!=999&&oyuncupokemonlar.get(2)!=999)){
        son++;
            kartsayisi--;
        atılankart=1;
        jButton11.setVisible(false);
        if(oyuncupokemonlar.get(0)==0){
        jButton17.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar1 = charmander.getHasarpuani();
            oyuncupokemonlar.set(0,999);
        }
        if(oyuncupokemonlar.get(0)==1){
        jButton17.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar1 = butterfree.getHasarpuani();
            oyuncupokemonlar.set(0,999);
        }
        if(oyuncupokemonlar.get(0)==2){
        jButton17.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar1 = bulbasaur.getHasarpuani();
            oyuncupokemonlar.set(0,999);
        }
        if(oyuncupokemonlar.get(0)==3){
        jButton17.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar1 = jigglypuff.getHasarpuani();
            oyuncupokemonlar.set(0,999);
        }
        if(oyuncupokemonlar.get(0)==4){
        jButton17.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar1 = meowth.getHasarpuani();
            oyuncupokemonlar.set(0,999);
        }
        if(oyuncupokemonlar.get(0)==5){
        jButton17.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar1 = pikachu.getHasarpuani();
            oyuncupokemonlar.set(0,999);
        }
        if(oyuncupokemonlar.get(0)==6){
        jButton17.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar1 = psyduck.getHasarpuani();
            oyuncupokemonlar.set(0,999);
        }
        if(oyuncupokemonlar.get(0)==7){
        jButton17.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar1 = squirtle.getHasarpuani();
            oyuncupokemonlar.set(0,999);
        }
        if(oyuncupokemonlar.get(0)==8){
        jButton17.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar1 = zubat.getHasarpuani();
            oyuncupokemonlar.set(0,999);
        }
        if(oyuncupokemonlar.get(0)==9){
        jButton17.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar1 = snorlax.getHasarpuani();
            oyuncupokemonlar.set(0,999);
        }
        
         x=rand.nextInt(3);
         while(pcpokemonlar.get(x)==999){
            x=rand.nextInt(3);
        }
         if(x==0){
             jButton14.setVisible(false);
             pcatılankart=1;
             if(pcpokemonlar.get(0)==0){
        jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==1){
        jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
           pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==2){
        jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                    pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==3){
        jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==4){
        jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2 = meowth.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==5){
        jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==6){
        jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==7){
        jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2= squirtle.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==8){
        jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2 = zubat.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==9){
        jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2= snorlax.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
         }
         if(x==1){
             jButton15.setVisible(false);
             pcatılankart=2;
             if(pcpokemonlar.get(1)==0){
        jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==1){
        jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
           pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==2){
        jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                    pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==3){
        jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==4){
        jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2 = meowth.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==5){
        jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==6){
        jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==7){
        jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2= squirtle.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==8){
        jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2 = zubat.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==9){
        jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2= snorlax.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
         }
         if(x==2){
             jButton16.setVisible(false);
             pcatılankart=3;
             if(pcpokemonlar.get(2)==0){
        jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==1){
        jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
           pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==2){
        jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                    pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==3){
        jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==4){
        jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2 = meowth.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==5){
        jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==6){
        jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==7){
        jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2= squirtle.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==8){
        jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2 = zubat.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==9){
        jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2= snorlax.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
         }
         if(yerdekipokemonlar.get(0)!=999 || yerdekipokemonlar.get(1)!=999 || yerdekipokemonlar.get(2)!=999 || yerdekipokemonlar.get(3)!=999 || yerdekipokemonlar.get(4)!=999 || yerdekipokemonlar.get(5)!=999 || yerdekipokemonlar.get(6)!=999 || yerdekipokemonlar.get(7)!=999 || yerdekipokemonlar.get(8)!=999 || yerdekipokemonlar.get(9)!=999){
         y=rand.nextInt(10);        
         while( y!=yerdekipokemonlar.get(0) && y!=yerdekipokemonlar.get(1) && y!=yerdekipokemonlar.get(2)&&y!=yerdekipokemonlar.get(3)&&y!=yerdekipokemonlar.get(4)&&y!=yerdekipokemonlar.get(5)&&y!=yerdekipokemonlar.get(6)&&y!=yerdekipokemonlar.get(7)&&y!=yerdekipokemonlar.get(8)&&y!=yerdekipokemonlar.get(9))
         {
             y=rand.nextInt(10);
         }
         if(pcatılankart==1) {
              jButton14.setVisible(true);
             if(y==0){
         jButton14.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
         pcpokemonlar.set(0,0);
         yerdekipokemonlar.set(0,999);
         jButton1.setVisible(false);
             }
             if(y==1){
         jButton14.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
         pcpokemonlar.set(0,1);
         yerdekipokemonlar.set(1,999);
         jButton2.setVisible(false);
             }
             if(y==2){
         jButton14.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
         pcpokemonlar.set(0,2);
         yerdekipokemonlar.set(2,999);
         jButton3.setVisible(false);
             }
             if(y==3){
         jButton14.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
         pcpokemonlar.set(0,3);
         yerdekipokemonlar.set(3,999);
         jButton4.setVisible(false);
             }
             if(y==4){
         jButton14.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
         pcpokemonlar.set(0,4);
         yerdekipokemonlar.set(4,999);
         jButton5.setVisible(false);
             }
             if(y==5){
         jButton14.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
         pcpokemonlar.set(0,5);
         yerdekipokemonlar.set(5,999);
         jButton6.setVisible(false);
             }
             if(y==6){
         jButton14.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
         pcpokemonlar.set(0,6);
         yerdekipokemonlar.set(6,999);
         jButton7.setVisible(false);
             }
             if(y==7){
         jButton14.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
         pcpokemonlar.set(0,7);
         yerdekipokemonlar.set(7,999);
         jButton8.setVisible(false);
             }
             if(y==8){
         jButton14.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
         pcpokemonlar.set(0,8);
         yerdekipokemonlar.set(8,999);
         jButton9.setVisible(false);
             }
             if(y==9){
         jButton14.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
         pcpokemonlar.set(0,9);
         yerdekipokemonlar.set(9,999);
         jButton10.setVisible(false);
             }
             
         }
         if(pcatılankart==2) {
              jButton15.setVisible(true);
             if(y==0){
         jButton15.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
         pcpokemonlar.set(1,0);
         yerdekipokemonlar.set(0,999);
         jButton1.setVisible(false);
             }
             if(y==1){
         jButton15.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
         pcpokemonlar.set(1,1);
         yerdekipokemonlar.set(1,999);
         jButton2.setVisible(false);
             }
             if(y==2){
         jButton15.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
         pcpokemonlar.set(1,2);
         yerdekipokemonlar.set(2,999);
         jButton3.setVisible(false);
             }
             if(y==3){
         jButton15.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
         pcpokemonlar.set(1,3);
         yerdekipokemonlar.set(3,999);
         jButton4.setVisible(false);
             }
             if(y==4){
         jButton15.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
         pcpokemonlar.set(1,4);
         yerdekipokemonlar.set(4,999);
         jButton5.setVisible(false);
             }
             if(y==5){
         jButton15.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
         pcpokemonlar.set(1,5);
         yerdekipokemonlar.set(5,999);
         jButton6.setVisible(false);
             }
             if(y==6){
         jButton15.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
         pcpokemonlar.set(1,6);
         yerdekipokemonlar.set(6,999);
         jButton7.setVisible(false);
             }
             if(y==7){
         jButton15.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
         pcpokemonlar.set(1,7);
         yerdekipokemonlar.set(7,999);
         jButton8.setVisible(false);
             }
             if(y==8){
         jButton15.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
         pcpokemonlar.set(1,8);
         yerdekipokemonlar.set(8,999);
         jButton9.setVisible(false);
             }
             if(y==9){
         jButton15.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
         pcpokemonlar.set(1,9);
         yerdekipokemonlar.set(9,999);
         jButton10.setVisible(false);
             }
             
         }
         if(pcatılankart==3) {
             jButton16.setVisible(true);
             if(y==0){
         jButton16.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
         pcpokemonlar.set(2,0);
         yerdekipokemonlar.set(0,999);
         jButton1.setVisible(false);
             }
             if(y==1){
         jButton16.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
         pcpokemonlar.set(2,1);
         yerdekipokemonlar.set(1,999);
         jButton2.setVisible(false);
             }
             if(y==2){
         jButton16.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
         pcpokemonlar.set(2,2);
         yerdekipokemonlar.set(2,999);
         jButton3.setVisible(false);
             }
             if(y==3){
         jButton16.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
         pcpokemonlar.set(2,3);
         yerdekipokemonlar.set(3,999);
         jButton4.setVisible(false);
             }
             if(y==4){
         jButton16.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
         pcpokemonlar.set(2,4);
         yerdekipokemonlar.set(4,999);
         jButton5.setVisible(false);
             }
             if(y==5){
         jButton16.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
         pcpokemonlar.set(2,5);
         yerdekipokemonlar.set(5,999);
         jButton6.setVisible(false);
             }
             if(y==6){
         jButton16.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
         pcpokemonlar.set(2,6);
         yerdekipokemonlar.set(6,999);
         jButton7.setVisible(false);
             }
             if(y==7){
         jButton16.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
         pcpokemonlar.set(2,7);
         yerdekipokemonlar.set(7,999);
         jButton8.setVisible(false);
             }
             if(y==8){
         jButton16.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
         pcpokemonlar.set(2,8);
         yerdekipokemonlar.set(8,999);
         jButton9.setVisible(false);
             }
             if(y==9){
         jButton16.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
         pcpokemonlar.set(2,9);
         yerdekipokemonlar.set(9,999);
         jButton10.setVisible(false);
             }
             
         }
         }
        if(hasar1>hasar2){
          oyuncuskor=oyuncuskor+5;
            System.out.println(""+hasar1+hasar2);
            
        }
        if(hasar2>hasar1){
            bilgskor=bilgskor+5;
            System.out.println(""+hasar1+hasar2);
            
        }
        if(son==5){
            if(bilgskor>oyuncuskor){
            JOptionPane.showMessageDialog(null, "Oyun Bitti Bilgisayar Kazandı! \n Bilgisayar:"+bilgskor+"\n "+insanoyuncusu.getOyuncuadi()+":"+oyuncuskor);
            dispose();}
            if(bilgskor<oyuncuskor){
            JOptionPane.showMessageDialog(null, "Oyun Bitti "+insanoyuncusu.getOyuncuadi()+" Kazandı! \n Bilgisayar:"+bilgskor+"\n"+insanoyuncusu.getOyuncuadi()+":"+oyuncuskor);
             dispose();}
            if(bilgskor==oyuncuskor){
                JOptionPane.showMessageDialog(null,"Oyun Bitti Berabere! \n Bilgisayar:"+bilgskor+"\n "+insanoyuncusu.getOyuncuadi()+":"+oyuncuskor);
            dispose();
            }
        }}
        System.out.println(""+oyuncuskor+bilgskor+son);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        
        
        if(kartsec==2){
            kartsayisi=3;
        }  
        System.out.println(""+oyuncuskor);   
        if(kartsayisi>2||(oyuncupokemonlar.get(0)!=999&&oyuncupokemonlar.get(1)!=999&&oyuncupokemonlar.get(2)!=999)){
           son++;
            kartsayisi--;
        atılankart=3;
        jButton13.setVisible(false);
        if(oyuncupokemonlar.get(2)==0){
        jButton17.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar1 = charmander.getHasarpuani();
            oyuncupokemonlar.set(2,999);
        }
        if(oyuncupokemonlar.get(2)==1){
        jButton17.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar1 = butterfree.getHasarpuani();
            oyuncupokemonlar.set(2,999);
        }
        if(oyuncupokemonlar.get(2)==2){
        jButton17.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar1 = bulbasaur.getHasarpuani();
                    oyuncupokemonlar.set(2,999);
        }
        if(oyuncupokemonlar.get(2)==3){
        jButton17.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar1 = jigglypuff.getHasarpuani();
            oyuncupokemonlar.set(2,999);
        }
        if(oyuncupokemonlar.get(2)==4){
        jButton17.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar1 = meowth.getHasarpuani();
            oyuncupokemonlar.set(2,999);
        }
        if(oyuncupokemonlar.get(2)==5){
        jButton17.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar1 = pikachu.getHasarpuani();
            oyuncupokemonlar.set(2,999);
        }
        if(oyuncupokemonlar.get(2)==6){
        jButton17.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar1 = psyduck.getHasarpuani();
            oyuncupokemonlar.set(2,999);
        }
        if(oyuncupokemonlar.get(2)==7){
        jButton17.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar1 = squirtle.getHasarpuani();
            oyuncupokemonlar.set(2,999);
        }
        if(oyuncupokemonlar.get(2)==8){
        jButton17.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar1 = zubat.getHasarpuani();
            oyuncupokemonlar.set(2,999);
        }
        if(oyuncupokemonlar.get(2)==9){
        jButton17.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar1 = snorlax.getHasarpuani();
            oyuncupokemonlar.set(2,999);
        }
        x=rand.nextInt(3);
         while(pcpokemonlar.get(x)==999){
            x=rand.nextInt(3);
        }
         if(x==0){
             jButton14.setVisible(false);
             pcatılankart=1;
             if(pcpokemonlar.get(0)==0){
        jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==1){
        jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
           pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==2){
        jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                    pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==3){
        jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==4){
        jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2 = meowth.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==5){
        jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==6){
        jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==7){
        jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2= squirtle.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==8){
        jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2 = zubat.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
        if(pcpokemonlar.get(0)==9){
        jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2= snorlax.getHasarpuani();
            pcpokemonlar.set(0,999);
        }
         }
         if(x==1){
             jButton15.setVisible(false);
             pcatılankart=2;
             if(pcpokemonlar.get(1)==0){
        jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==1){
        jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
           pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==2){
        jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                    pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==3){
        jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==4){
        jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2 = meowth.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==5){
        jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==6){
        jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==7){
        jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2= squirtle.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==8){
        jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2 = zubat.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
        if(pcpokemonlar.get(1)==9){
        jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2= snorlax.getHasarpuani();
            pcpokemonlar.set(1,999);
        }
         }
         if(x==2){
             jButton16.setVisible(false);
             pcatılankart=3;
             if(pcpokemonlar.get(2)==0){
        jButton18.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            hasar2 = charmander.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==1){
        jButton18.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            hasar2 = butterfree.getHasarpuani();
           pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==2){
        jButton18.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            hasar2 = bulbasaur.getHasarpuani();
                    pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==3){
        jButton18.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            hasar2 = jigglypuff.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==4){
        jButton18.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            hasar2 = meowth.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==5){
        jButton18.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            hasar2 = pikachu.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==6){
        jButton18.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            hasar2 = psyduck.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==7){
        jButton18.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            hasar2= squirtle.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==8){
        jButton18.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            hasar2 = zubat.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
        if(pcpokemonlar.get(2)==9){
        jButton18.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            hasar2= snorlax.getHasarpuani();
            pcpokemonlar.set(2,999);
        }
         }
         if(yerdekipokemonlar.get(0)!=999 || yerdekipokemonlar.get(1)!=999 || yerdekipokemonlar.get(2)!=999 || yerdekipokemonlar.get(3)!=999 || yerdekipokemonlar.get(4)!=999 || yerdekipokemonlar.get(5)!=999 || yerdekipokemonlar.get(6)!=999 || yerdekipokemonlar.get(7)!=999 || yerdekipokemonlar.get(8)!=999 || yerdekipokemonlar.get(9)!=999){
         y=rand.nextInt(10);        
         while( y!=yerdekipokemonlar.get(0) && y!=yerdekipokemonlar.get(1) && y!=yerdekipokemonlar.get(2)&&y!=yerdekipokemonlar.get(3)&&y!=yerdekipokemonlar.get(4)&&y!=yerdekipokemonlar.get(5)&&y!=yerdekipokemonlar.get(6)&&y!=yerdekipokemonlar.get(7)&&y!=yerdekipokemonlar.get(8)&&y!=yerdekipokemonlar.get(9))
         {
             y=rand.nextInt(10);
         }
         if(pcatılankart==1) {
              jButton14.setVisible(true);
             if(y==0){
         jButton14.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
         pcpokemonlar.set(0,0);
         yerdekipokemonlar.set(0,999);
         jButton1.setVisible(false);
             }
             if(y==1){
         jButton14.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
         pcpokemonlar.set(0,1);
         yerdekipokemonlar.set(1,999);
         jButton2.setVisible(false);
             }
             if(y==2){
         jButton14.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
         pcpokemonlar.set(0,2);
         yerdekipokemonlar.set(2,999);
         jButton3.setVisible(false);
             }
             if(y==3){
         jButton14.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
         pcpokemonlar.set(0,3);
         yerdekipokemonlar.set(3,999);
         jButton4.setVisible(false);
             }
             if(y==4){
         jButton14.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
         pcpokemonlar.set(0,4);
         yerdekipokemonlar.set(4,999);
         jButton5.setVisible(false);
             }
             if(y==5){
         jButton14.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
         pcpokemonlar.set(0,5);
         yerdekipokemonlar.set(5,999);
         jButton6.setVisible(false);
             }
             if(y==6){
         jButton14.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
         pcpokemonlar.set(0,6);
         yerdekipokemonlar.set(6,999);
         jButton7.setVisible(false);
             }
             if(y==7){
         jButton14.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
         pcpokemonlar.set(0,7);
         yerdekipokemonlar.set(7,999);
         jButton8.setVisible(false);
             }
             if(y==8){
         jButton14.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
         pcpokemonlar.set(0,8);
         yerdekipokemonlar.set(8,999);
         jButton9.setVisible(false);
             }
             if(y==9){
         jButton14.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
         pcpokemonlar.set(0,9);
         yerdekipokemonlar.set(9,999);
         jButton10.setVisible(false);
             }
             
         }
         if(pcatılankart==2) {
              jButton15.setVisible(true);
             if(y==0){
         jButton15.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
         pcpokemonlar.set(1,0);
         yerdekipokemonlar.set(0,999);
         jButton1.setVisible(false);
             }
             if(y==1){
         jButton15.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
         pcpokemonlar.set(1,1);
         yerdekipokemonlar.set(1,999);
         jButton2.setVisible(false);
             }
             if(y==2){
         jButton15.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
         pcpokemonlar.set(1,2);
         yerdekipokemonlar.set(2,999);
         jButton3.setVisible(false);
             }
             if(y==3){
         jButton15.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
         pcpokemonlar.set(1,3);
         yerdekipokemonlar.set(3,999);
         jButton4.setVisible(false);
             }
             if(y==4){
         jButton15.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
         pcpokemonlar.set(1,4);
         yerdekipokemonlar.set(4,999);
         jButton5.setVisible(false);
             }
             if(y==5){
         jButton15.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
         pcpokemonlar.set(1,5);
         yerdekipokemonlar.set(5,999);
         jButton6.setVisible(false);
             }
             if(y==6){
         jButton15.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
         pcpokemonlar.set(1,6);
         yerdekipokemonlar.set(6,999);
         jButton7.setVisible(false);
             }
             if(y==7){
         jButton15.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
         pcpokemonlar.set(1,7);
         yerdekipokemonlar.set(7,999);
         jButton8.setVisible(false);
             }
             if(y==8){
         jButton15.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
         pcpokemonlar.set(1,8);
         yerdekipokemonlar.set(8,999);
         jButton9.setVisible(false);
             }
             if(y==9){
         jButton15.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
         pcpokemonlar.set(1,9);
         yerdekipokemonlar.set(9,999);
         jButton10.setVisible(false);
             }
             
         }
         if(pcatılankart==3) {
             jButton16.setVisible(true);
             if(y==0){
         jButton16.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
         pcpokemonlar.set(2,0);
         yerdekipokemonlar.set(0,999);
         jButton1.setVisible(false);
             }
             if(y==1){
         jButton16.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
         pcpokemonlar.set(2,1);
         yerdekipokemonlar.set(1,999);
         jButton2.setVisible(false);
             }
             if(y==2){
         jButton16.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
         pcpokemonlar.set(2,2);
         yerdekipokemonlar.set(2,999);
         jButton3.setVisible(false);
             }
             if(y==3){
         jButton16.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
         pcpokemonlar.set(2,3);
         yerdekipokemonlar.set(3,999);
         jButton4.setVisible(false);
             }
             if(y==4){
         jButton16.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
         pcpokemonlar.set(2,4);
         yerdekipokemonlar.set(4,999);
         jButton5.setVisible(false);
             }
             if(y==5){
         jButton16.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
         pcpokemonlar.set(2,5);
         yerdekipokemonlar.set(5,999);
         jButton6.setVisible(false);
             }
             if(y==6){
         jButton16.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
         pcpokemonlar.set(2,6);
         yerdekipokemonlar.set(6,999);
         jButton7.setVisible(false);
             }
             if(y==7){
         jButton16.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
         pcpokemonlar.set(2,7);
         yerdekipokemonlar.set(7,999);
         jButton8.setVisible(false);
             }
             if(y==8){
         jButton16.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
         pcpokemonlar.set(2,8);
         yerdekipokemonlar.set(8,999);
         jButton9.setVisible(false);
             }
             if(y==9){
         jButton16.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
         pcpokemonlar.set(2,9);
         yerdekipokemonlar.set(9,999);
         jButton10.setVisible(false);
             }
             
         }
         }
        if(hasar1>hasar2){
            oyuncuskor=oyuncuskor+5;
            System.out.println(""+hasar1+hasar2);
            
        }
        if(hasar2>hasar1){
            bilgskor=bilgskor+5;
            System.out.println(""+hasar1+hasar2);
            
        }
        if(son==5){
            if(bilgskor>oyuncuskor){
            JOptionPane.showMessageDialog(null, "Oyun Bitti Bilgisayar Kazandı! \n Bilgisayar:"+bilgskor+"\n "+insanoyuncusu.getOyuncuadi()+":"+oyuncuskor);
            dispose();}
            if(bilgskor<oyuncuskor){
            JOptionPane.showMessageDialog(null, "Oyun Bitti "+insanoyuncusu.getOyuncuadi()+" Kazandı! \n Bilgisayar:"+bilgskor+"\n "+insanoyuncusu.getOyuncuadi()+":"+oyuncuskor);
            dispose();}
            if(bilgskor==oyuncuskor){
                JOptionPane.showMessageDialog(null,"Oyun Bitti Berabere! \n Bilgisayar:"+bilgskor+"\n "+insanoyuncusu.getOyuncuadi()+":"+oyuncuskor);
            dispose();
            }
        }
        
        }System.out.println(""+oyuncuskor+bilgskor+son);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(kartsayisi<3){
        yerdekipokemonlar.set(0,999);
        kartsayisi++;
        kartsec++;
        if(atılankart==1){
            jButton11.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            oyuncupokemonlar.set(0,0);
            jButton11.setVisible(true);
            jButton1.setVisible(false);
        }
        if(atılankart==2){
            jButton12.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            oyuncupokemonlar.set(1,0);
            jButton12.setVisible(true);
            jButton1.setVisible(false);
        }
        if(atılankart==3){
            jButton13.setIcon(new javax.swing.ImageIcon(charmander.getImage()));
            oyuncupokemonlar.set(2,0);
            jButton13.setVisible(true);
            jButton1.setVisible(false);
        }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(kartsayisi<3){
        yerdekipokemonlar.set(1,999);
        kartsayisi++;
        kartsec++;
        if(atılankart==1){
            jButton11.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            oyuncupokemonlar.set(0,1);
            jButton11.setVisible(true);
            jButton2.setVisible(false);
        }
        if(atılankart==2){
            jButton12.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            oyuncupokemonlar.set(1,1);
            jButton12.setVisible(true);
            jButton2.setVisible(false);
        }
        if(atılankart==3){
            jButton13.setIcon(new javax.swing.ImageIcon(butterfree.getImage()));
            oyuncupokemonlar.set(2,1);
            jButton13.setVisible(true);
            jButton2.setVisible(false);
        }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(kartsayisi<3){
        yerdekipokemonlar.set(2,999);
       kartsayisi++;
       kartsec++;
        if(atılankart==1){
            jButton11.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            oyuncupokemonlar.set(0,2);
            jButton11.setVisible(true);
            jButton3.setVisible(false);
        }
        if(atılankart==2){
            jButton12.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            oyuncupokemonlar.set(1,2);
            jButton12.setVisible(true);
            jButton3.setVisible(false);
        }
        if(atılankart==3){
            jButton13.setIcon(new javax.swing.ImageIcon(bulbasaur.getImage()));
            oyuncupokemonlar.set(2,2);
            jButton13.setVisible(true);
            jButton3.setVisible(false);
        }}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      if(kartsayisi<3){
        yerdekipokemonlar.set(3,999);
       kartsayisi++;
       kartsec++;
        if(atılankart==1){
            jButton11.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            oyuncupokemonlar.set(0,3);
            jButton11.setVisible(true);
            jButton4.setVisible(false);
        }
        if(atılankart==2){
            jButton12.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            oyuncupokemonlar.set(1,3);
            jButton12.setVisible(true);
            jButton4.setVisible(false);
        }
        if(atılankart==3){
            jButton13.setIcon(new javax.swing.ImageIcon(jigglypuff.getImage()));
            oyuncupokemonlar.set(2,3);
            jButton13.setVisible(true);
            jButton4.setVisible(false);
        }}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       if(kartsayisi<3){
        yerdekipokemonlar.set(6,999);
        kartsayisi++;
        kartsec++;
        if(atılankart==1){
            jButton11.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            oyuncupokemonlar.set(0,6);
            jButton11.setVisible(true);
            jButton7.setVisible(false);
        }
        if(atılankart==2){
            jButton12.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            oyuncupokemonlar.set(1,6);
            jButton12.setVisible(true);
            jButton7.setVisible(false);
        }
        if(atılankart==3){
            jButton13.setIcon(new javax.swing.ImageIcon(psyduck.getImage()));
            oyuncupokemonlar.set(2,6);
            jButton13.setVisible(true);
            jButton7.setVisible(false);
        }}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(kartsayisi<3){
        yerdekipokemonlar.set(7,999);
        kartsayisi++;
        kartsec++;
        if(atılankart==1){
            jButton11.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            oyuncupokemonlar.set(0,7);
            jButton11.setVisible(true);
            jButton8.setVisible(false);
        }
        if(atılankart==2){
            jButton12.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            oyuncupokemonlar.set(1,7);
            jButton12.setVisible(true);
            jButton8.setVisible(false);
        }
        if(atılankart==3){
            jButton13.setIcon(new javax.swing.ImageIcon(squirtle.getImage()));
            oyuncupokemonlar.set(2,7);
            jButton13.setVisible(true);
            jButton8.setVisible(false);
        }}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       if(kartsayisi<3){
        yerdekipokemonlar.set(8,999);
       kartsayisi++;
       kartsec++;
        if(atılankart==1){
            jButton11.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            oyuncupokemonlar.set(0,8);
            jButton11.setVisible(true);
            jButton9.setVisible(false);
        }
        if(atılankart==2){
            jButton12.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            oyuncupokemonlar.set(1,8);
            jButton12.setVisible(true);
            jButton9.setVisible(false);
        }
        if(atılankart==3){
            jButton13.setIcon(new javax.swing.ImageIcon(zubat.getImage()));
            oyuncupokemonlar.set(2,8);
            jButton13.setVisible(true);
            jButton9.setVisible(false);
        }}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(kartsayisi<3){
        yerdekipokemonlar.set(9,999);
        kartsayisi++;
        kartsec++;
        if(atılankart==1){
            jButton11.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            oyuncupokemonlar.set(0,9);
            jButton11.setVisible(true);
            jButton10.setVisible(false);
        }
        if(atılankart==2){
            jButton12.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            oyuncupokemonlar.set(1,9);
            jButton12.setVisible(true);
            jButton10.setVisible(false);
        }
        if(atılankart==3){
            jButton13.setIcon(new javax.swing.ImageIcon(snorlax.getImage()));
            oyuncupokemonlar.set(2,9);
            jButton13.setVisible(true);
            jButton10.setVisible(false);
        }}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(kartsayisi<3){
        yerdekipokemonlar.set(4,999);
        kartsayisi++;
        kartsec++;
        if(atılankart==1){
            jButton11.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            oyuncupokemonlar.set(0,4);
            jButton11.setVisible(true);
            jButton5.setVisible(false);
        }
        if(atılankart==2){
            jButton12.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            oyuncupokemonlar.set(1,4);
            jButton12.setVisible(true);
            jButton5.setVisible(false);
        }
        if(atılankart==3){
            jButton13.setIcon(new javax.swing.ImageIcon(meowth.getImage()));
            oyuncupokemonlar.set(2,4);
            jButton13.setVisible(true);
            jButton5.setVisible(false);
        }}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(kartsayisi<3){
        yerdekipokemonlar.set(5,999);
        kartsayisi++;
        kartsec++;
        if(atılankart==1){
            jButton11.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            oyuncupokemonlar.set(0,5);
            jButton11.setVisible(true);
            jButton6.setVisible(false);
        }
        if(atılankart==2){
            jButton12.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            oyuncupokemonlar.set(1,5);
            jButton12.setVisible(true);
            jButton6.setVisible(false);
        }
        if(atılankart==3){
            jButton13.setIcon(new javax.swing.ImageIcon(pikachu.getImage()));
            oyuncupokemonlar.set(2,5);
            jButton13.setVisible(true);
            jButton6.setVisible(false);
        }}
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Playervspc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Playervspc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Playervspc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Playervspc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

 
 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Playervspc().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables


}
